#!/usr/bin/env bash
baseDir=$(pwd);
cd projects/ngx-app-msg
version=$(npm version patch)
cd $baseDir
rm -rf dist
ng build ngx-app-msg --prod
rm -rf docs
ng build --prod --aot --base-href /ngx-app-msg/
cp LICENSE README.md dist/ngx-app-msg
git add -A
git commit -m "release $version"
git tag $version
git push origin master
git push --tags
cd dist/ngx-app-msg
npm publish --access public
cd $baseDir
git status
